import React, {useState} from 'react';
import {ArrowLeft, ArrowRight, CheckCircle2} from 'lucide-react';
import {customers,services,regions} from './data';

export function ResetPassword({go,notify}){
  const [password,setPassword]=useState('');
  const [confirm,setConfirm]=useState('');
  const [error,setError]=useState('');
  return <div className="auth"><div className="auth-brand"><h1>Password baru</h1><p>Langkah terakhir pemulihan akun Nirwana.</p></div><div className="auth-form-wrap"><form className="auth-form" onSubmit={e=>{e.preventDefault();if(password.length<6||password!==confirm){setError('Password minimal 6 karakter dan konfirmasi harus sama.');return}notify('Password demo berhasil diperbarui');go('/login')}}><a className="back-link" href="/forgot-password" onClick={e=>{e.preventDefault();go('/forgot-password')}}><ArrowLeft size={16}/> Kembali</a><h2>Buat password baru</h2><label className="field"><span>Password baru</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6}/></label><label className="field"><span>Konfirmasi password</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<p className="form-error">{error}</p>}<button className="btn full" type="submit">Simpan dan masuk <ArrowRight size={16}/></button><p className="auth-hint">Simulasi UI; password tidak dikirim atau disimpan.</p></form></div></div>
}

export function FirstLogin({go,notify}){
  const [password,setPassword]=useState('');
  const [confirm,setConfirm]=useState('');
  const [error,setError]=useState('');
  return <div className="auth"><div className="auth-brand"><h1>Selamat datang di Nirwana</h1><p>Siapkan password pribadi untuk pertama kali masuk.</p></div><div className="auth-form-wrap"><form className="auth-form" onSubmit={e=>{e.preventDefault();if(password.length<6||password!==confirm){setError('Password minimal 6 karakter dan konfirmasi harus sama.');return}notify('Akun demo siap digunakan');go('/client/dashboard')}}><h2>Aktivasi akun pertama</h2><label className="field"><span>Password baru</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6}/></label><label className="field"><span>Ulangi password</span><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<p className="form-error">{error}</p>}<button className="btn full" type="submit">Lanjut ke portal <ArrowRight size={16}/></button><p className="auth-hint">Aktivasi ini hanya simulasi.</p></form></div></div>
}

export function CustomerForm({role,go,notify}){
  const [form,setForm]=useState({name:'',phone:'',region:'Bandung Utara',address:'',joined:new Date().toISOString().slice(0,10),account:true});
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  return <div className="narrow-page"><button className="back-link" onClick={()=>go(`/${role}/customers`)}><ArrowLeft size={16}/> Pelanggan</button><div className="page-heading"><div><div className="eyebrow">DATA OPERASIONAL</div><h1>Tambah pelanggan</h1><p>Isi identitas dan kontak pelanggan fiktif untuk simulasi.</p></div></div><form className="panel form-panel" onSubmit={e=>{e.preventDefault();const id=Math.max(0,...customers.map(c=>c.id))+1;customers.push({id,name:form.name.trim(),phone:form.phone.trim(),region:form.region,address:form.address.trim(),joined:form.joined,services:0,status:form.account?'Aktif':'Nonaktif'});notify('Pelanggan demo berhasil ditambahkan');go(`/${role}/customers/${id}`)}}><label className="field"><span>Nama lengkap</span><input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label className="field"><span>Nomor WhatsApp</span><input required minLength={9} type="tel" value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label className="field"><span>Wilayah</span><select value={form.region} onChange={e=>set('region',e.target.value)}>{regions.slice(1).map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>Alamat</span><textarea required rows={3} value={form.address} onChange={e=>set('address',e.target.value)}/></label><label className="field"><span>Tanggal registrasi</span><input required type="date" value={form.joined} onChange={e=>set('joined',e.target.value)}/></label><label className="field"><span>Dokumen identitas (opsional, demo)</span><input type="file" accept="image/*,.pdf"/></label><label className="field checkbox-field"><span><input type="checkbox" checked={form.account} onChange={e=>set('account',e.target.checked)}/> Buat akun pelanggan demo</span></label><div className="form-actions"><button type="button" className="btn soft" onClick={()=>go(`/${role}/customers`)}>Batal</button><button type="submit" className="btn">Simpan pelanggan <ArrowRight size={16}/></button></div></form></div>
}

export function ServiceForm({role,go,notify}){
  const [form,setForm]=useState({owner:customers[0].name,name:'Internet Rumah',package:'Home Internet',region:'Bandung Utara',address:'',coord:'',installed:new Date().toISOString().slice(0,10),status:'Aktif'});
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  return <div className="narrow-page"><button className="back-link" onClick={()=>go(`/${role}/services`)}><ArrowLeft size={16}/> Layanan</button><div className="page-heading"><div><div className="eyebrow">DATA OPERASIONAL</div><h1>Tambah layanan</h1><p>Satu layanan terhubung ke satu pelanggan.</p></div></div><form className="panel form-panel" onSubmit={e=>{e.preventDefault();const id=Math.max(0,...services.map(s=>s.id))+1;services.push({id,number:`SRV-2026-${String(id).padStart(3,'0')}`,...form,coord:form.coord||'—'});const customer=customers.find(c=>c.name===form.owner);if(customer)customer.services+=1;notify('Layanan demo berhasil ditambahkan');go(`/${role}/services/${id}`)}}><label className="field"><span>Pelanggan</span><select value={form.owner} onChange={e=>set('owner',e.target.value)}>{customers.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Nama layanan</span><input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label className="field"><span>Paket / jenis layanan</span><input required value={form.package} onChange={e=>set('package',e.target.value)}/></label><label className="field"><span>Status administratif</span><select value={form.status} onChange={e=>set('status',e.target.value)}><option>Aktif</option><option>Nonaktif</option></select></label><label className="field"><span>Wilayah</span><select value={form.region} onChange={e=>set('region',e.target.value)}>{regions.slice(1).map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>Alamat pemasangan</span><textarea required rows={3} value={form.address} onChange={e=>set('address',e.target.value)}/></label><label className="field"><span>Koordinat (opsional)</span><input value={form.coord} onChange={e=>set('coord',e.target.value)} placeholder="-6.90, 107.60"/></label><label className="field"><span>Tanggal pemasangan</span><input required type="date" value={form.installed} onChange={e=>set('installed',e.target.value)}/></label><div className="form-actions"><button type="button" className="btn soft" onClick={()=>go(`/${role}/services`)}>Batal</button><button type="submit" className="btn">Simpan layanan <CheckCircle2 size={16}/></button></div></form></div>
}

export function TechnicianProfile(){return <><div className="page-heading"><div><div className="eyebrow">AKUN TEKNISI</div><h1>Profil Saya</h1><p>Informasi akun demo teknisi lapangan.</p></div></div><section className="panel"><div className="panel-head"><h2>Data teknisi</h2></div><dl className="details"><div><dt>Nama</dt><dd>Andi Saputra</dd></div><div><dt>Peran</dt><dd>Teknisi</dd></div><div><dt>Wilayah</dt><dd>Bandung Utara</dd></div><div><dt>Nomor telepon</dt><dd>0822 •••• 1265</dd></div></dl></section></>}
