import React, {useState} from 'react';
import {FileText,Plus} from 'lucide-react';
import {canCorrectVoucher} from './domain';

export default function VoucherPage({role,vouchers,changeVoucher,notify}){
  const [dialog,setDialog]=useState(null);
  const [quantity,setQuantity]=useState(1);
  const [note,setNote]=useState('');
  const [history,setHistory]=useState([{date:'04 Okt 2026 · 09:42',name:'Voucher 10 GB',type:'Penambahan',amount:'+20',by:'Nadia Amelia',note:'Penyesuaian stok'}]);
  const commit=e=>{e.preventDefault();if(!canCorrectVoucher(role)||!dialog)return;const delta=Number(quantity)*(dialog.type==='Tambah'?1:-1);if(dialog.type==='Kurangi'&&vouchers[dialog.index].count<Number(quantity)){notify('Jumlah melebihi stok tersedia');return}changeVoucher(dialog.index,delta);setHistory([{date:'Baru saja',name:vouchers[dialog.index].name,type:dialog.type==='Tambah'?'Penambahan':'Pengurangan',amount:(delta>0?'+':'')+delta,by:role==='admin'?'Nadia Amelia':'Nadia Putri',note:note.trim()},...history]);setDialog(null);setQuantity(1);setNote('')};
  return <><div className="page-heading"><div><div className="eyebrow">SALDO PERUSAHAAN</div><h1>Stok Voucher</h1><p>Saldo berdasarkan jenis dan riwayat mutasi.</p></div></div><div className="metrics three voucher-grid">{vouchers.map((v,index)=><div className="voucher-card" key={v.name}><div className="voucher-card-top"><div className="voucher-icon"><FileText size={20}/></div><span className="badge">{v.count<100?'Stok rendah':'Tersedia'}</span></div><span>{v.name}</span><strong>{v.count}</strong><small>voucher tersedia</small>{canCorrectVoucher(role)&&<div className="voucher-actions"><button className="btn soft" onClick={()=>setDialog({index,type:'Tambah'})}><Plus size={15}/> Tambah</button><button className="btn soft" disabled={v.count===0} onClick={()=>setDialog({index,type:'Kurangi'})}>− Kurangi</button></div>}</div>)}</div><section className="panel"><div className="panel-head"><h2>Riwayat Mutasi</h2></div><div className="table-scroll"><table><thead><tr>{['Tanggal','Voucher','Tipe','Jumlah','Pengguna','Catatan'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{history.map((h,index)=><tr key={index}><td>{h.date}</td><td>{h.name}</td><td>{h.type}</td><td>{h.amount}</td><td>{h.by}</td><td>{h.note}</td></tr>)}</tbody></table></div></section>{role==='technician'&&<p className="small-note">Teknisi dapat melihat saldo tanpa melakukan koreksi.</p>}{dialog&&<div className="modal-backdrop" onClick={()=>setDialog(null)}><form className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()} onSubmit={commit}><h2>{dialog.type} voucher</h2><p>{vouchers[dialog.index].name} · stok saat ini {vouchers[dialog.index].count}</p><label className="field"><span>Jumlah</span><input type="number" min="1" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="field"><span>Catatan</span><textarea required rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button className="btn soft" type="button" onClick={()=>setDialog(null)}>Batal</button><button className="btn" type="submit">Konfirmasi</button></div></form></div>}</>
}
